# Generated by Django 3.1.4 on 2021-01-12 06:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20210112_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_pdf',
            field=models.FileField(upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
